import { ExperienceSectionType } from '@/lib/types/sections'

export const experienceSection: ExperienceSectionType = {
    title: "where i've worked",
    experiences: [
    {
        company: 'Plus Talent Co., Ltd.',
        companyUrl: 'https://www.plustalent.co/about-us',
        projectUrl: 'https://dev.architecture-master.com/',
        projectname: 'Clean Architecture Learning',
        projectname_ja: 'クリーンアーキテクチャ学習プラットフォーム',
        role: 'Fullstack Engineer',
        role_ja: 'フルスタックエンジニア',
        started: 'October 2025',
        started_ja: '2025年10月',
        upto: 'December 2025 ( current )',
        upto_ja: '2025年12月（現在）',
        duration: '3 months',
        duration_ja: '3ヶ月',
        tasks: [
        'Creating an interactive educational platform for teaching Clean Architecture principles.',
        '- Built a multi-step learning curriculum with 6+ interactive lessons covering Entity, Use Case, Interface, and Framework layers',
        '- Implemented URL-based routing with SEO optimization (8+ indexable pages) and sticky navigation for seamless user experience',
        '- Designed responsive UI components with dark/light mode support and progress tracking system',
        '- Created subscription management system with multiple pricing tiers (Free, Premium, Enterprise)',
        '- Developed GitHub-integrated code review features with AI-powered feedback system',
        'Tech Stack: TypeScript, React, Next.js, Prisma, PostgreSQL, Firebase, Docker, E2E Testing, GCP',
        'Colleagues: With senior architect'
        ],
        tasks_ja: [
        'クリーンアーキテクチャの原則を教えるためのインタラクティブな教育プラットフォームの開発',
        '- Entity、Use Case、Interface、Frameworkレイヤーをカバーする6つ以上のインタラクティブなレッスンを含む段階的な学習カリキュラムを構築',
        '- SEO最適化（8つ以上のインデックス可能なページ）とスティッキーナビゲーションを備えたURLベースのルーティングを実装し、シームレスなユーザーエクスペリエンスを実現',
        '- ダーク/ライトモードサポートと進捗追跡システムを備えたレスポンシブUIコンポーネントを設計',
        '- 複数の価格帯（無料、プレミアム、エンタープライズ）を持つサブスクリプション管理システムを構築',
        '- AIを活用したフィードバックシステムを備えたGitHub統合コードレビュー機能を開発',
        '技術スタック: TypeScript, React, Next.js, Prisma, PostgreSQL, Firebase, Docker, E2Eテスト, GCP',
        '同僚: シニアアーキテクトと協力'
        ],
    },
    {
        company: 'Plus Talent Co., Ltd.',
        companyUrl: 'https://www.plustalent.co/about-us',
        projectUrl: 'https://prd-clean-rental-management--prod-clean-rentalspace-manage.asia-east1.hosted.app/',
        projectname: 'Clean Rentalspace Management System',
        projectname_ja: 'クリーンレンタルスペース管理システム',
        role: 'Fullstack Engineer',
        role_ja: 'フルスタックエンジニア',
        started: 'September 2025',
        started_ja: '2025年9月',
        upto: 'November 2025',
        upto_ja: '2025年11月',
        duration: '2 months',
        duration_ja: '2ヶ月',
        tasks: [
        'Developed a comprehensive rental space cleaning management platform as a full-stack developer.',
        '- Built booking management system with dynamic scheduling and cleaner assignment features',
        '- Implemented admin dashboard for managing bookings, users, stores, and financial adjustments',
        '- Developed automated daily reporting system using Firebase Functions with scheduled tasks',
        '- Created RESTful API endpoints with JWT authentication and role-based access control',
        '- Designed database schema with Prisma ORM and implemented migration strategies',
        '- Set up CI/CD pipeline with GitHub Actions and automated deployment via Firebase App Hosting',
        'Tech Stack: TypeScript, React, Next.js, Prisma, PostgreSQL, Firebase, Docker, E2E Testing, GCP',
        'Colleagues: With Senior Architect, Sonnet 4.5 AI'
        ],
        tasks_ja: [
        'レンタルスペースのクリーニング管理プラットフォームをフルスタック開発者として開発',
        '- 動的スケジューリングとクリーナー割り当て機能を備えた予約管理システムを構築',
        '- 予約、ユーザー、店舗、財務調整を管理する管理者ダッシュボードを実装',
        '- Firebase Functionsを使用したスケジュールタスクによる自動日次レポートシステムを開発',
        '- JWT認証とロールベースのアクセス制御を備えたRESTful APIエンドポイントを作成',
        '- Prisma ORMでデータベーススキーマを設計し、マイグレーション戦略を実装',
        '- GitHub Actionsを使用したCI/CDパイプラインを設定し、Firebase App Hosting経由で自動デプロイ',
        '技術スタック: TypeScript, React, Next.js, Prisma, PostgreSQL, Firebase, Docker, E2Eテスト, GCP',
        '同僚: シニアアーキテクト、Sonnet 4.5 AIと協力'
        ],
    },
    {
        company: 'Brycen Myanmar Co., Ltd.',
        companyUrl: 'https://www.brycenmyanmar.com.mm/',
        projectUrl: 'https://www.suntory.co.jp/',
        projectname: 'Suntory Softdrink Distribution System',
        projectname_ja: 'サントリーソフトドリンク流通システム',
        role: 'Senior Software Engineer',
        role_ja: 'シニアソフトウェアエンジニア',
        started: 'July 2024',
        started_ja: '2024年7月',
        upto: 'August 2025',
        upto_ja: '2025年8月',
        duration: '13 months',
        duration_ja: '13ヶ月',
        tasks: [
        'Collaborating with the Japanese IT team, I design batch processes for CSV downloads, manage documentation, and implement new features',
        'Batch Processing: Develop shell scripts for CSV batches as per the 【出荷】バッチ概要',
        'Documentation: Prepare screen designs (画面設計書), test cases, and evidence (エビデンス) for each feature',
        'Team Collaboration: Work closely with the Japanese and Myanmar teams (Project Manager, Leader, Subleader, developers, and fresher supports)',
        'Release & Improvement: Validate, finalize, and release features jointly to ensure system quality and efficiency',
        ],
        tasks_ja: [
        '日本のITチームと協力し、CSVダウンロードのバッチ処理を設計し、ドキュメントを管理し、新機能を実装',
        'バッチ処理: 【出荷】バッチ概要に従ってCSVバッチ用のシェルスクリプトを開発',
        'ドキュメント: 各機能の画面設計書、テストケース、エビデンスを準備',
        'チーム協力: 日本とミャンマーのチーム（プロジェクトマネージャー、リーダー、サブリーダー、開発者、新人サポート）と緊密に連携',
        'リリース・改善: 機能を共同で検証、確定、リリースし、システムの品質と効率を確保',
        ],
    },
    {
        company: 'Brycen Myanmar Co., Ltd.',
        companyUrl: 'https://www.brycenmyanmar.com.mm/',
        projectUrl: 'https://www.brycen.co.jp/',
        projectname: 'HRMOS Recruitment Management System',
        projectname_ja: 'HRMOS採用管理システム',
        role: 'Senior Software Engineer',
        role_ja: 'シニアソフトウェアエンジニア',
        started: 'April 2024',
        started_ja: '2024年4月',
        upto: 'June 2024',
        upto_ja: '2024年6月',
        duration: '2 months',
        duration_ja: '2ヶ月',
        tasks: [
        'As a Senior Software engineer, I collaborated with the Japanese IT team to design batch processes for CSV downloads, manage documentation, and implement new features.',
        'Batch Processing: Develop shell scripts for CSV batches as per the 【出荷】バッチ概要',
        'Documentation: Prepare screen designs (画面設計書), test cases, and evidence (エビデンス) for each feature',
        'Team Collaboration: Work closely with the Japanese and Myanmar teams (Project Manager, Leader, Subleader, developers, and fresher supports)',
        'Release & Improvement: Validate, finalize, and release features jointly to ensure system quality and efficiency',
        ],
        tasks_ja: [
        'シニアソフトウェアエンジニアとして、日本のITチームと協力してCSVダウンロードのバッチ処理を設計し、ドキュメントを管理し、新機能を実装',
        'バッチ処理: 【出荷】バッチ概要に従ってCSVバッチ用のシェルスクリプトを開発',
        'ドキュメント: 各機能の画面設計書、テストケース、エビデンスを準備',
        'チーム協力: 日本とミャンマーのチーム（プロジェクトマネージャー、リーダー、サブリーダー、開発者、新人サポート）と緊密に連携',
        'リリース・改善: 機能を共同で検証、確定、リリースし、システムの品質と効率を確保',
        ],
    },
    {
        company: 'Brycen Myanmar Co., Ltd.',
        companyUrl: 'https://www.brycenmyanmar.com.mm/',
        projectUrl: 'https://www.scroll360.jp/',
        projectname: 'Scroll-360 Ecommerce System',
        projectname_ja: 'Scroll-360 ECシステム',
        role: 'Senior Software Engineer',
        role_ja: 'シニアソフトウェアエンジニア',
        started: 'August 2023',
        started_ja: '2023年8月',
        upto: 'February 2024',
        upto_ja: '2024年2月',
        duration: '6 months',
        duration_ja: '6ヶ月',
        tasks: [
        'As a Senior engineer, I collaborated with the Japanese IT team to design batch processes for CSV downloads, manage documentation, and implement new features.',
        'Batch Processing: Develop shell scripts for CSV batches as per the 【出荷】バッチ概要',
        'Documentation: Prepare screen designs (画面設計書), test cases, and evidence (エビデンス) for each feature',
        'Team Collaboration: Work closely with the Japanese and Myanmar teams (Project Manager, Leader, Subleader, developers, and fresher supports)',
        'Release & Improvement: Validate, finalize, and release features jointly to ensure system quality and efficiency',
        ],
        tasks_ja: [
        'シニアエンジニアとして、日本のITチームと協力してCSVダウンロードのバッチ処理を設計し、ドキュメントを管理し、新機能を実装',
        'バッチ処理: 【出荷】バッチ概要に従ってCSVバッチ用のシェルスクリプトを開発',
        'ドキュメント: 各機能の画面設計書、テストケース、エビデンスを準備',
        'チーム協力: 日本とミャンマーのチーム（プロジェクトマネージャー、リーダー、サブリーダー、開発者、新人サポート）と緊密に連携',
        'リリース・改善: 機能を共同で検証、確定、リリースし、システムの品質と効率を確保',
        ],
    },
    {
        company: 'VisibleOne Co., Ltd.',
        companyUrl: 'https://visibleone.com/',
        projectUrl: 'https://lyhealthy.com/en',
        projectname: 'LYHealthy Platform',
        projectname_ja: 'LYHealthyプラットフォーム',
        role: 'Web Developer',
        role_ja: 'ウェブ開発者',
        started: 'January 2024',
        started_ja: '2024年1月',
        upto: 'July 2024',
        upto_ja: '2024年7月',
        duration: '6 months',
        duration_ja: '6ヶ月',
        tasks: [
            'As a developer, I built comprehensive healthcare and e-commerce platforms with multiple service modules.',
            'Main Services Modules such as Body-Check, DNA-Check, Nutritionist, Vaccine, Children Treatment and Emotional Therapy',
            'Social Sharing Modules for Event Seminars, Blogs and Videos',
            'An E-commerce Shop featuring product listings, filtered by product type with integrated services',
            'Dynamic content and images, multiple pages, and complex business logic are all key components of our project',
            'Tech Stack: JavaScript, React, Next.js, jQuery Ajax, PHP, Laravel',
            'Features: E-commerce, Membership, Shipping, Checkout, Coupon system',
            'Colleagues: UI/UX designer, frontend, backend developer, server team, quality assurance and project manager',
            'Project timeline: 1 year with two main sprints (each sprint includes bug fixes, issue resolution, server deployment, client meetings)'
        ],
        tasks_ja: [
            '開発者として、複数のサービスモジュールを備えた包括的なヘルスケアおよびEコマースプラットフォームを構築',
            'Body-Check、DNA-Check、栄養士、ワクチン、小児治療、感情療法などの主要サービスモジュール',
            'イベントセミナー、ブログ、ビデオのソーシャルシェアリングモジュール',
            '統合サービスを備えた製品タイプ別にフィルタリングされた製品リストを特徴とするEコマースショップ',
            'ダイナミックなコンテンツと画像、複数ページ、複雑なビジネスロジックがプロジェクトの主要コンポーネント',
            '技術スタック: JavaScript, React, Next.js, jQuery Ajax, PHP, Laravel',
            '機能: Eコマース、メンバーシップ、配送、チェックアウト、クーポンシステム',
            '同僚: UI/UXデザイナー、フロントエンド、バックエンド開発者、サーバーチーム、品質保証、プロジェクトマネージャー',
            'プロジェクトタイムライン: 1年間で2つの主要スプリント（各スプリントにはバグ修正、問題解決、サーバーデプロイ、クライアントミーティングを含む）'
        ],
    },
    {
        company: 'VisibleOne Co., Ltd.',
        companyUrl: 'https://visibleone.com/',
        projectUrl: 'https://www.methodist-centre.com/en',
        projectname: 'Methodist Centre Multi-language Platform',
        projectname_ja: 'メソジストセンター多言語プラットフォーム',
        role: 'Web Developer',
        role_ja: 'ウェブ開発者',
        started: 'August 2023',
        started_ja: '2023年8月',
        upto: 'December 2023',
        upto_ja: '2023年12月',
        duration: '5 months',
        duration_ja: '5ヶ月',
        tasks: [
            'As a developer, I built a comprehensive multi-language platform supporting 5 languages using Laravel ORM Eloquent.',
            'Developed database structure for multiple languages (English, Simplified Chinese, Traditional Chinese, Arabic, and Indonesian) using ORM Eloquent',
            'Service Modules (health-care, talent-care, youth-family-community-care, and elderly-care)',
            'Mc People Modules (become mc, growth mc, and life mc)',
            'Mc Co-creation Modules (mc-schools, mc-corporate, mc-coorganization, and mc-you)',
            'Mc Story Modules (Mc Journey, Mission, Corporate Governance, and public material)',
            'Press Release Modules (keeping-up-to-date, media coverage, press release, mc-publication, and m-channel)',
            'Tech Stack: Vanilla JS, jQuery Ajax, PHP, Laravel',
            'Dynamic content and images, multiple pages, and complex business logic are all key components of our project'
        ],
        tasks_ja: [
            '開発者として、Laravel ORM Eloquentを使用して5つの言語をサポートする包括的な多言語プラットフォームを構築',
            'ORM Eloquentを使用した複数言語（英語、簡体字中国語、繁体字中国語、アラビア語、インドネシア語）のデータベース構造を開発',
            'サービスモジュール（医療、タレントケア、若者・家族・コミュニティケア、高齢者ケア）',
            'Mc Peopleモジュール（become mc、growth mc、life mc）',
            'Mc Co-creationモジュール（mc-schools、mc-corporate、mc-coorganization、mc-you）',
            'Mc Storyモジュール（Mc Journey、Mission、Corporate Governance、public material）',
            'プレスリリースモジュール（keeping-up-to-date、media coverage、press release、mc-publication、m-channel）',
            '技術スタック: Vanilla JS, jQuery Ajax, PHP, Laravel',
            'ダイナミックなコンテンツと画像、複数ページ、複雑なビジネスロジックがプロジェクトの主要コンポーネント'
        ],
    },
    {
        company: 'VisibleOne Co., Ltd.',
        companyUrl: 'https://visibleone.com/',
        projectUrl: 'https://www.sundai.ac.jp/',
        projectname: 'Sundai University Examination System',
        projectname_ja: '駿台大学受験専門システム',
        role: 'Web Developer',
        role_ja: 'ウェブ開発者',
        started: 'March 2021',
        started_ja: '2021年3月',
        upto: 'August 2023',
        upto_ja: '2023年8月',
        duration: '2 years 5 months',
        duration_ja: '2年5ヶ月',
        tasks: [
        'Developed student data and complex database structure as assigned by the senior developer',
        'Developed backend with RESTful API (Service and Repository) using PHP (Laravel framework)',
        'Developed frontend with Axios (data binding) using JavaScript (Vue framework)',
        'Developed using the Singleton design pattern (SOLID principles) for a high-performance and scalable PHP structure',
        'Tech Stack: JavaScript, Vue, PHP, Laravel',
        'Key Features: PDF downloads, email system, and Excel data management for students and teachers',
        ],
        tasks_ja: [
        'シニア開発者の指示に従って学生データと複雑なデータベース構造を開発',
        'PHP（Laravelフレームワーク）を使用してRESTful API（サービスとリポジトリ）でバックエンドを開発',
        'JavaScript（Vueフレームワーク）を使用してAxios（データバインディング）でフロントエンドを開発',
        '高性能でスケーラブルなPHP構造のためにシングルトンデザインパターン（SOLID原則）を使用して開発',
        '技術スタック: JavaScript, Vue, PHP, Laravel',
        '主な機能: PDFダウンロード、メールシステム、学生と教師のためのExcelデータ管理',
        ],
    },
    {
        company: 'ATYS Japanese Language School',
        companyUrl: 'https://www.atys-academy.org/',
        projectname: 'Japanese Language Study & Part-time Work',
        projectname_ja: '日本語学習・アルバイト',
        role: 'Student',
        role_ja: '学生',
        started: 'July 2018',
        started_ja: '2018年7月',
        upto: 'November 2019',
        upto_ja: '2019年11月',
        duration: '1 year 4 months',
        duration_ja: '1年4ヶ月',
        tasks: [
        'Learning Japanese Language (N5, N4, N3) できる日本語 (1:00 pm to 5 pm) Mon to Fri',
        'Part-time: Sushi-Ro スシロー restaurant - Fried Fish, Potato (18:00-20:00) Mon-Tue-Wed',
        'Part-time: Lawson ローソン convenience store - Cashier (6:00-12:00) Wed-Thu-Fri',
        ],
        tasks_ja: [
        '日本語学習（N5、N4、N3）できる日本語（午後1時～午後5時）月～金',
        'アルバイト: スシローレストラン - 揚げ物、ポテト（18:00～20:00）月・火・水',
        'アルバイト: ローソンコンビニ - レジ（6:00～12:00）水・木・金',
        ],
    },
    {
        company: 'Tomorrow Technology',
        companyUrl: 'https://opencorporates.com/companies/mm/1091-1998-1999',
        projectname: 'Technical Support & Installation Services',
        projectname_ja: '技術サポート・インストールサービス',
        role: 'Service Technician',
        role_ja: 'サービス技術者',
        started: 'January 2016',
        started_ja: '2016年1月',
        upto: 'December 2017',
        upto_ja: '2017年12月',
        duration: '2 years',
        duration_ja: '2年',
        tasks: [
        'Installation of Windows OS and Applications',
        'Installation of Mobile Firmware and Applications',
        ],
        tasks_ja: [
        'Windows OSおよびアプリケーションのインストール',
        'モバイルファームウェアおよびアプリケーションのインストール',
        ],
    },
    ],
};